### ISSUE TITLE
add_submodule directive?

### ISSUE THREAD

**Issue by MichaelVoelkel** [TheAssemblyArmada/crashpad-cmake#1]
Hi,

thanks for your attempt to make Crashpad workable in an easier way (it is really a mess to set it up manually).

What do you mean with `add_submodule` directive. Do you mean `add_subdirectory` in CMake? Is really nothing else necessary?

Edit:
Doing it this way, I get several errors on macOS... "unknown typename FARPROC"... and I cannot find include directories? So, I need to add "add_subdirectory"? Things like this should be added to the doc

**Comment by OmniBlade** [comment]
You are right, its a mistake in the documentation, I'll get that fixed. Thanks for the feedback, I wasn't sure if I was just doing this for my own requirements or if anyone else would find it useful.

**Comment by MichaelVoelkel** [comment]
For now I stick with the manual process although it is also messy :) but yeah, if it works reliable, it is definitely a big plus!! But somehow automatising this whole "gn gen" + "ninja" stuff within a CMake project needs a lot of custom commands, I presume... Thanks for your work!

**Comment by OmniBlade** [comment]
I've basically replaced the gn stuff with equivalent cmake directives, gn isn't used when you use this CMake wrapper. I've created a PR to update the documentation and make things a bit clearer. I might add an small example application to make it clear how its supposed to be used.

**Comment by MichaelVoelkel** [comment]
Ah, very cool! Do you test on Win/Mac or both? I could give it a try when it's updated

**Comment by OmniBlade** [comment]
I've only tested on windows and linux since I don't have a mac, its entirely possible I've not included everything that is needed on macOS or not linked everything required.

**Comment by OmniBlade** [comment]
I've updated the readme now, I'll look at adding a test program and CI build validation, thanks for the feedback.
